server:
  port: 9099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
spring:
  rabbitmq:
    addresses: localhost:5672
  application:
    name: notification